### ISSUE TITLE
macOS: Cannot find source file: mach_excServer.c

### ISSUE THREAD

**Issue by stevielavern** [quarkslab/QBDI#26]
Hello,

Compiling QDBI (master branch) on macOS, it seems that the source file "mach_excServer.c" is missing:

-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.10", minimum required is "2.7")
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found suitable version "2.7.10", minimum required is "2.7")
-- Configuring done
CMake Error at tools/QBDIPreload/CMakeLists.txt:14 (add_library):
  Cannot find source file:

    mach_excServer.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: Cannot determine link language for target "QBDIPreload".
CMake Error: CMake can not determine linker language for target: QBDIPreload

Thank you.

**Comment by haxelion** [comment]
That's a strange error. So basically this file should be autogenerated from the mig interface definition:     https://github.com/quarkslab/QBDI/blob/master/tools/QBDIPreload/CMakeLists.txt#L7

Can you check these two things?

1. You have the mig program and that the following command generates `mach_excServer.c`:
```bash
   mig /usr/include/mach/mach_exc.defs
```
2. The file  `mach_excServer.c` exists in `<your build directory>/tools/QBDIPreload`. For me I get:
```bash
% ls build/tools/QBDIPreload 
CMakeFiles          Makefile            cmake_install.cmake libQBDIPreload.a    mach_exc.h          mach_excServer.c    mach_excUser.c
```

**Comment by stevielavern** [comment]
Thank you haxelion,

The /usr/include directory does not exist anymore by default in the last releases of macOS. The "command line developer tools" package needs to be installed to have the /usr/include directory and the mach files.

**Comment by haxelion** [comment]
Yes but you'll need those to compile it anyway ;-)
Maybe we should mark that in the README.

**Comment by nezetic** [comment]
iOS support is still totally experimental (that's why there's no developer preview yet). And it's not documented at all.

Compilation has various additional dependencies, like "command line developer tools", but also a patched iPhoneOS SDK (with headers copied from macOS), etc.

The usage also has some requirements, like to run the Frida server in background (because it handles RWX pages for us, which is very practical as we can inject in any binary without adding new entitlements to it).

With incoming ARM Thumb2 support, we will definitely try to have a binary release for iOS (and proper documentation).

**Comment by nezetic** [comment]
Documentation has been made more explicit about requirements on macOS (dca2862).
