### ISSUE TITLE
SegFault on Python instrumentation

### ISSUE THREAD

**Issue by commial** [quarkslab/QBDI#33]
Hi,

First, thanks for your project, it seems really great.
I tried to instrument the Python2 binary, using the example script:
```Python
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import pyqbdi

def mycb(vm, gpr, fpr, data):
    inst = vm.getInstAnalysis()
    print "0x%x: %s" % (inst.address, inst.disassembly)
    return pyqbdi.CONTINUE

def pyqbdipreload_on_run(vm, start, stop):
    vm.addCodeCB(pyqbdi.PREINST, mycb, None)
    vm.run(start, stop)
```

Running `LD_PRELOAD=/usr/lib/libpyqbdi.so PYQBDI_TOOL=./test.py /usr/bin/python2` leads to a Segmentation Fault error.

A few information:
* Python version: 2.7.14
* Install done with the .deb package
* Ubuntu 17.10

I can try to dig more into if you're not able to reproduce the crash.

**Comment by Axi0m-S** [comment]
I can also reproduce this crash and investigated the issue.
Actually, using pyQBDI to instrument python binary does not work really well, because it is not reentrant. It means that you will instrument some python methods (eg : **PyObject_Call**), but you will also use those methods in your instrumentation, which will put pyQBDI in an unstable state. (see attached logs) 

If you really do want to instrument python2 binary, you may want to try [QBDIPreload](https://qbdi.quarkslab.com/docs/qbdi_preload.html) (I just tried it and works well).


ax@ax:~/Documents/Instrumentation Team/QBDI/issue33$ gdb /usr/bin/python2 -c core
[New LWP 12483]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
bt
Core was generated by `/usr/bin/python2'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005565a3aee3fd in **PyObject_Call** ()
gef➤  bt
#0  0x00005565a3aee3fd in **PyObject_Call** ()
#1  0x00005565a3b0bec0 in PyEval_CallObjectWithKeywords ()
#2  0x00007ff2192d6579 in QBDI::Bindings::Python::trampoline (vm=<optimized out>, gprState=<optimized out>, fprState=0x7ff215d01000, multipleData=0x5565a5dcd3d0) at /home/ax/Documents/QBDI/tools/pyqbdi/pyqbdi.cpp:1649
#3  0x00007ff217cf1ebd in QBDI::ExecBlock::execute (this=0x5565a6058490) at /home/ax/Documents/QBDI/src/ExecBlock/ExecBlock.cpp:201
#4  0x00007ff217cefbf4 in QBDI::Engine::run (this=0x5565a5d104b0, start=start@entry=0x5565a3adb3d0, stop=stop@entry=0x7ff21840f2b1) at /home/ax/Documents/QBDI/src/Engine/Engine.cpp:380
#5  0x00007ff217cce8d8 in QBDI::VM::run (this=0x5565a5d10480, start=0x5565a3adb3d0, stop=stop@entry=0x7ff21840f2b1) at /home/ax/Documents/QBDI/src/Engine/VM.cpp:157
#6  0x00007ff2192dc811 in QBDI::Bindings::Python::vm_run (self=0x7ff21966f0f0, args=<optimized out>) at /home/ax/Documents/QBDI/tools/pyqbdi/pyqbdi.cpp:2586
#7  0x00005565a3b01b9a in PyEval_EvalFrameEx ()
#8  0x00005565a3affd45 in PyEval_EvalCodeEx ()
#9  0x00005565a3b1ca7e in ?? ()
#10 0x00005565a3aee413 in **PyObject_Call** ()
#11 0x00005565a3b0bec0 in PyEval_CallObjectWithKeywords ()
#12 0x00007ff2192e085f in QBDI::Bindings::Python::execScript (stop=0x7ff21840f2b1, start=0x5565a3adb3d0, vm=0x5565a5d10480, fileName=<optimized out>) at /home/ax/Documents/QBDI/tools/pyqbdi/pyqbdi.cpp:3283
#13 QBDI::qbdipreload_on_run (vm=0x5565a5d10480, start=start@entry=0x5565a3adb3d0, stop=0x7ff21840f2b1) at /home/ax/Documents/QBDI/tools/pyqbdi/pyqbdi.cpp:3345
#14 0x00007ff2192e1f48 in catchEntrypoint (argc=<optimized out>, argv=<optimized out>) at /home/ax/Documents/QBDI/tools/QBDIPreload/src/linux_preload.c:199
#15 0x0000000000000000 in ?? ()

**Comment by commial** [comment]
Thanks for this detailed answer.

I may go with QBDIPreload, except that from what I understand, the instrumentation will only start from the main code and I'm also interested by the loader stuff. A mix of the two approach should probably work :)

**Comment by haxelion** [comment]
Unfortunately the python bindings are bindings on QBDIPreload so neither of them allow to trace the loader.
Can you tell me which parts of the loader interests you? Is it before the entrypoint or from the entrypoint?
In the first case there is nothing QBDI can do for you because the only way is to reimplement a loader inside the DBI (like valgrind does). In the second case it is possibly with libQBDIPreload with some tweakings.

**Comment by nezetic** [comment]
Tracing the loader requires something more powerful than using LD_PRELOAD to take control of the execution. I know Frida provides early control over the execution (at least on macOS). But the issue will be that QBDI needs more than the libc to run.

**Comment by haxelion** [comment]
This issue is kind of related with #27 : these limitations should be better documented.
